service: learn-openai-api
frameworkVersion: '3'

provider:
  name: aws

plugins:
  - serverless-dotenv-plugin

functions:
  animalnames:
    description: "The animal names hello world snippet"
    runtime: nodejs14.x
    handler: lambdas/node/animalnames.handler
    events:
      - httpApi:
          path: /api/openai/animalnames
          method: get
  animalnames2:
    description: "The animal names hello world snippet"
    runtime: nodejs14.x
    handler: lambdas/node/animalnames2.handler
    events:
      - httpApi:
          path: /api/openai/animalnames2
          method: get
