service: learn-openai-api
frameworkVersion: '3'

provider:
  name: aws

plugins:
  - serverless-dotenv-plugin

functions:
  animalnames:
    description: "The animal names hello world snippet"
    runtime: nodejs14.x
    handler: lambdas/node/animalnames.handler
    events:
      - httpApi:
          path: /api/openai/animalnames
          method: get
  completions:
    description: "Calls the OpenAI API completions endpoint which uses the GPT-3 (Generative Pre-trained Transformer 3) model to generate text completions"
    runtime: nodejs14.x
    handler: lambdas/node/completions.handler
    events:
      - httpApi:
          path: /api/openai/completions
          method: get
