service: learn-openai-api
frameworkVersion: '3'

provider:
  name: aws

plugins:
  - serverless-dotenv-plugin

functions:
  animalnames:
    description: "Simple example showing use of the OpenAI API for the animal names getting started tutorial"
    runtime: nodejs14.x
    handler: lambdas/node/animalnames.handler
    events:
      - httpApi:
          method: get
          path: /api/openai/animalnames
  completions:
    description: "Calls the OpenAI API completions endpoint which uses the GPT-3 (Generative Pre-trained Transformer 3) model to generate text completions"
    runtime: nodejs14.x
    handler: lambdas/node/completions.handler
    events:
      - httpApi:
          method: get
          path: /api/openai/completions

